borg_passphrase: "{{ vault_borg_passphrase }}"
wireguard_type: client
wireguard_address: 192.168.211.90
wireguard_private_key: "{{ vault_wireguard_private_key }}"
wireguard_public_key: U9Zkgf0iZ6nKuARUH3qTowgoZLFrrWE2blO6GKqMGnI=
wireguard_endpoint_port: 51820
hack_vouchers_tmp_emission_token: "{{ vault_hack_vouchers_tmp_emission_token }}"