$ANSIBLE_VAULT;1.1;AES256
63316636316664653838643531316232656433333837636463356133336562363862333966653437
6634356563303566396131666131376539393434333930640a303562633133643537633234343231
35363837633737623937626538303630623235373139323733646431343732353265653734346130
6664646464653434350a333862316433653537656531373861376634663838393434356335336362
30663036333235363336616564353866666432363531626439616461623362663561386537313163
33353631343437303839623161303461313832386535326335653866393038366465356539353963
31386663343063613634373764356330326562343062366336623234303063363132383337626431
66383861363837326435653434376565653464323666363364313234376563373533306165633331
32663335303336613937623062336237633430383634353836366666383665313235643635303639
32386434643437653830666262663337343338363831666465363538386137646464653736643265
62383533313838366231646461386136303137623234613332363964626133306562646139373232
38343064376234316634356634303265366335383563346137396139376661306439643630323261
6563
