# This guide has been useful in setting up InfluxDB / telegraf / grafaana
# https://www.howtoforge.com/tutorial/how-to-install-tig-stack-telegraf-influxdb-and-grafana-on-ubuntu-1804/

- name: Add InfluxDB / Telegraf repository key
  apt_key:
      url: 'https://repos.influxdata.com/influxdb.key'
      state: present

- name: Add InfluxDB / Telegraf Repository
  apt_repository:
      repo: 'deb https://repos.influxdata.com/debian buster stable'
      state: present

- name: Add Grafana repository key
  apt_key:
      url: 'https://packages.grafana.com/gpg.key'
      state: present

- name: Add Grafana Repository
  apt_repository:
      repo: 'deb https://packages.grafana.com/oss/deb stable main'
      state: present

- name: Update grafana root URL
  replace:
    path: /etc/grafana/grafana.ini
    replace: 'root_url = http://localhost:3000/grafana/'
    regexp: 'root_url.*'

- name: Allow Grafana to be served as subpath
  replace:
    path: /etc/grafana/grafana.ini
    replace: 'serve_from_sub_path = True'
    regexp: 'serve_from_sub_path.*'

- name: Install InfluxDB / Telegraf / Grafana
  apt:
    update_cache: yes
    pkg:
      - influxdb
      - telegraf
      - grafana

- name: Start InfluxDB
  systemd:
      name: influxdb
      enabled: true
      state: started

- name: Start telegraf
  systemd:
      name: telegraf
      enabled: true
      state: started

- name: Start Grafana
  systemd:
      name: grafana-server
      enabled: true
      state: started
