- include_tasks:
    file: "main{{ deployment_suffix }}.yml"
  tags:
    - nginx-vouchers-v2


- name: Debug BBB vouchers2_ssl_snippet_conf
  ansible.builtin.debug:
    var: vouchers2_ssl_snippet_conf

- name: Debug BBB vouchers2_server_fqdn
  ansible.builtin.debug:
    var: vouchers2_server_fqdn


- name: Instanciate vouchers2 nginx config
  template:
    src: ldt-vouchers-v2.conf.j2
    dest: /etc/nginx/sites-available/ldt-vouchers-v2.conf
    mode: u=r,g=r,o=r
  notify:
    - nginx changed
  tags:
    - nginx-vouchers-v2

- name: Enable vouchers2.epicerieledetour.org nginx configuration file
  file:
    src: /etc/nginx/sites-available/ldt-vouchers-v2.conf
    dest: /etc/nginx/sites-enabled/ldt-vouchers-v2.conf
    state: link
  notify:
    - nginx changed
  tags:
    - nginx-vouchers-v2
